"""事件级联合 Transformer V2 的独立实现。"""

from .state import (
    COMMITMENT_SECONDS,
    MAX_TASK_OWNERS,
    EventStateTensors,
    build_commitment_mask,
    build_replan_order,
)
from .reward import (
    GAEOutput,
    build_completion_event_rewards,
    completion_potential,
    completion_task_weights,
    terminal_completion_quality,
    time_aware_gae,
)
from .transition import (
    TRANSITION_SCHEMA_VERSION,
    ActionTrace,
    EventTransition,
    JointEventAction,
    transition_schema_definition,
    transition_schema_fingerprint,
)
from .observation import (
    EventPolicyObservation,
    stack_event_observations,
)
from .runtime_state import (
    EventRuntimeState,
    EventType,
    RuntimeEvent,
    RuntimeSnapshot,
    TerminationReason,
)
from .basilisk_runtime import (
    BasiliskEventRuntime,
    BasiliskSceneBackend,
    CompletionSnapshot,
    RuntimeStep,
    load_runtime_statistics,
)
from .rollout import (
    StoredEventStep,
    SynchronousRuntimeSlot,
    collect_synchronous_rollout,
    replay_rollout_log_probs,
)
from .ppo import (
    PPOConfig,
    PPOUpdateMetrics,
    PPOUpdateRejected,
    RolloutTargets,
    SynchronousPPOTrainer,
    clipped_ppo_objective,
    compute_rollout_targets,
    event_action_component_counts,
)
from .appo import (
    APPOConfig,
    APPODone,
    APPORolloutChunk,
    APPOSnapshot,
    APPOUpdateMetrics,
    APPOWorkerError,
    AsynchronousPPOLearner,
    PolicyLagFilterResult,
    SharedPolicyRefresh,
    SharedPolicyStore,
    collect_appo_actor_chunk,
    filter_policy_lag,
    run_appo_actor_loop,
)
from .checkpoint import (
    APPO_CHECKPOINT_VERSION,
    APPOCounters,
    APPORestore,
    SYNC_PPO_CHECKPOINT_VERSION,
    SyncPPOCounters,
    SyncPPORestore,
    build_appo_checkpoint,
    build_sync_ppo_checkpoint,
    capture_rng_state,
    config_fingerprint,
    load_appo_checkpoint,
    load_sync_ppo_checkpoint,
    restore_rng_state,
    save_checkpoint_atomic,
)
from .backbone import Stage3BackboneOutput, Stage3FeatureBackbone
from .critic import (
    CentralizedValueCritic,
    EventStateEncoder,
    EventStateEncoding,
)
from .actor import (
    ActionEvaluation,
    ActorOutput,
    AutoregressiveJointActor,
)
from .model import EventActorCriticOutput, EventJointActorCritic
from .dataset import (
    EventV2OfflineDataset,
    OfflineEventBatch,
    OfflineEventTargets,
    build_capped_owner_counts,
    build_commitment_targets,
    compress_expert_actions_to_events,
)
from .offline import OfflineLosses, event_v2_offline_loss

__all__ = [
    'COMMITMENT_SECONDS',
    'MAX_TASK_OWNERS',
    'EventStateTensors',
    'build_commitment_mask',
    'build_replan_order',
    'GAEOutput',
    'build_completion_event_rewards',
    'completion_potential',
    'completion_task_weights',
    'terminal_completion_quality',
    'time_aware_gae',
    'TRANSITION_SCHEMA_VERSION',
    'ActionTrace',
    'EventTransition',
    'JointEventAction',
    'transition_schema_definition',
    'transition_schema_fingerprint',
    'EventPolicyObservation',
    'stack_event_observations',
    'EventRuntimeState',
    'EventType',
    'RuntimeEvent',
    'RuntimeSnapshot',
    'TerminationReason',
    'BasiliskEventRuntime',
    'BasiliskSceneBackend',
    'CompletionSnapshot',
    'RuntimeStep',
    'load_runtime_statistics',
    'StoredEventStep',
    'SynchronousRuntimeSlot',
    'collect_synchronous_rollout',
    'replay_rollout_log_probs',
    'PPOConfig',
    'PPOUpdateMetrics',
    'PPOUpdateRejected',
    'RolloutTargets',
    'SynchronousPPOTrainer',
    'clipped_ppo_objective',
    'compute_rollout_targets',
    'event_action_component_counts',
    'APPOConfig',
    'APPODone',
    'APPORolloutChunk',
    'APPOSnapshot',
    'APPOUpdateMetrics',
    'APPOWorkerError',
    'AsynchronousPPOLearner',
    'PolicyLagFilterResult',
    'SharedPolicyRefresh',
    'SharedPolicyStore',
    'collect_appo_actor_chunk',
    'filter_policy_lag',
    'run_appo_actor_loop',
    'APPO_CHECKPOINT_VERSION',
    'APPOCounters',
    'APPORestore',
    'SYNC_PPO_CHECKPOINT_VERSION',
    'SyncPPOCounters',
    'SyncPPORestore',
    'build_appo_checkpoint',
    'build_sync_ppo_checkpoint',
    'capture_rng_state',
    'config_fingerprint',
    'load_appo_checkpoint',
    'load_sync_ppo_checkpoint',
    'restore_rng_state',
    'save_checkpoint_atomic',
    'Stage3BackboneOutput',
    'Stage3FeatureBackbone',
    'CentralizedValueCritic',
    'EventStateEncoder',
    'EventStateEncoding',
    'ActionEvaluation',
    'ActorOutput',
    'AutoregressiveJointActor',
    'EventActorCriticOutput',
    'EventJointActorCritic',
    'EventV2OfflineDataset',
    'OfflineEventBatch',
    'OfflineEventTargets',
    'build_capped_owner_counts',
    'build_commitment_targets',
    'compress_expert_actions_to_events',
    'OfflineLosses',
    'event_v2_offline_loss',
]
